name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
    - name: Install angular-cli-ghpages
      run: npm install -g angular-cli-ghpages

    - name: Build Angular app
      run: npm run build 
    - name: Build Angular app
      run: ng build --configuration production --base-href=/Ai_Comp_Angualr/

    - name: Deploy to GitHub Pages
      uses: angular-schule/angular-cli-ghpages@v1
      with:
        baseHref: /Ai_Comp_Angualr/
        buildDir: dist/comp_ai/browser